# This is a basic workflow to help you get started with Actions

name: gfwlist2ros

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the rm branch
on:
  #push:
  #  branches: [ master ]
#  pull_request:
#    branches: [ rm ]
  schedule:
    - cron: '0 21 * * *'
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run gfwlist2ros.sh
      run: bash gfwlist2ros.sh
    
    - name: Commit files
      run: |
        git config --local user.email "goodffd@gmail.com"
        git config --local user.name "goodffd"
        git commit -m "Add changes" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
